version: '3'
services:
  postgres:
    image: postgres:10.2
    ports:
      - 5432:5432
    volumes:
      - "./postgresql.conf:/postgresql.conf"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_DB: blog
    command: "-c config_file=/postgresql.conf"